### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by bertho-zero** [stefanoruth/react-portal-ssr#5]
This package needs to be babelified, at least for the server side.

**Comment by stefanoruth** [comment]
You are more than welcome to submit a pr or produce an example with the exception :), personally i have et running on a few projects without the issue but i am at the most tile compiling from esnext.

**Comment by bertho-zero** [comment]
https://unpkg.com/@stefanoruth/react-portal-ssr@2.0.3/server.js
https://unpkg.com/@stefanoruth/react-portal-ssr@2.0.3/dist/server.js

The following 2 files are executed with Node.js and contain import / export.

The example is run with `ts-node -r esm`, this is something I don't want for my project.

**Comment by bertho-zero** [comment]
I will create my own fork.

**Comment by stefanoruth** [comment]
Have published a new version with cjs as the default for server-side parts version is 2.1.0
